### ISSUE TITLE
Generate resources podspec or inject them directly into Xcode project

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#10]
We're currently adding resources to the Xcode project by manually writing a `.podspec`:

https://github.com/microsoft/react-native-test-app/blob/03b6479ba5b4c2d5b4bd20e15d7b0b26fc9bd0e0/example/Example-dev.podspec#L19

It should be possible to generate this file, or alternatively, inject them directly into the project from the manifest, e.g.:

```json
{
  "name": "Example",
  "displayName": "Example",
  "components": {},
  "resources": [
    "dist/assets",
    "dist/main.jsbundle"
  ]
}

```

**Comment by alloy** [comment]
A podspec is just a Ruby file that gets evaluated, so you can dynamically read in a JSON manifest and populate the `resources` attribute that way.
