### ISSUE TITLE
Support multi-tasking on iPad

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-test-app#1031]
### Proposal

React-Native-test-app doesn't support becoming a [Slide Over window](https://support.apple.com/guide/ipad/switch-an-app-window-to-slide-over-ipadfe7c65e9/ipados) on iPad. 

### Alternatives

N/A

### Implementation Details

Quick google sent me here: https://spin.atomicobject.com/2021/05/05/add-support-split-view-slide-over-react-native-app/
It looks like we need to check all 4 "Device Orientation" options in our Xcode target. Looking at FluentUI React Native's test app, I see that we are missing one:
![image](https://user-images.githubusercontent.com/6722175/182248798-da4f7ad0-dbc6-4510-bf51-ec36b83ce1a9.png)

Once checked, I can confirm that we know support multi-tasking / Slide Over windows (though now we must fix our UI 😅)
![image](https://user-images.githubusercontent.com/6722175/182249337-034595bd-17d5-46c3-a386-d8bc27c29029.png)

### Additional Context

This isn't blocking anything. Just noticed it while I was debugging. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Let me know if this works 👆

**Comment by Saadnajmi** [comment]
Yep! Just made the same change in FURN's local copy of react-native-test-app and this worked!
