### ISSUE TITLE
macOS: mouseDown always fires React menu

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-test-app#1039]
### What happened?

My guess is this is because of this [line](https://github.com/microsoft/react-native-test-app/blob/trunk/macos/ReactTestApp/ViewController.swift#L34) introduced by #1001 

mouseDown always shows the reactMenu, even if running in single-app mode where we are not on the get started screen. This also gets in the way of e2e testing as the left click isn't getting registered properly anymore. Commenting out the `mouseDown` override seems to fix it. 

### Version

1.6.1

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 79.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Launch [FluentTester on macOS](https://github.com/microsoft/fluentui-react-native/blob/main/apps/fluent-tester/docs/macos.md) (though this should work in any RNTA based test app
1. Left click on any blank space

Expected:
- Nothing happens

Actual:
- See NSMenu for react options. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saadnajmi** [comment]
Could you add items to the default RCTDevMenu instead?

https://github.com/facebook/react-native/blob/2e649006f1a78539f5504bce79cbd51816679e13/React/CoreModules/RCTDevMenu.h#L76

**Comment by tido64** [comment]
Can you see if this fixes the issue 👆

**Comment by Saadnajmi** [comment]
Yep! Seems good :)
