### ISSUE TITLE
Android app doesn't work on release

### ISSUE THREAD

**Issue by alfonsocj** [microsoft/react-native-test-app#1096]
### What happened?

When building Android on release:
- It shows a blank screen if `singleApp` is used.
- It asks to connect to metro when `singleApp` is not used.

### Version

1.6.13

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 241.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.18 - ~/.yvm/shim/yarn
    npm: 8.18.0 - ~/src/datetimepicker/node_modules/.bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fonz/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: 25.0.8775105
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: ^0.69.5 => 0.69.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- clone https://github.com/alfonsocj/datetimepicker/tree/react-native-test-app-bug/example2
- use branch `react-native-test-app-bug`
- cd example2
- yarn install
- run `./gradlew assembleRelease` in `example2/android`
- install apk (`example2/android/app/build/outputs/apk/release/app-release.apk`) to emulator

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alfonsocj** [comment]
👋 @tido64 @kelset when you have some time could you help me reproduce this? 🙏  I'm currently trying to change the example app for [datetimepicker](https://github.com/react-native-datetimepicker/datetimepicker) to use react-native-test-app and I need a release build for Detox.

**Comment by tido64** [comment]
Hi @alfonsocj, let me know if I misunderstand your scenario:

- You're trying to build a release build because Detox requires it
- You don't want to use a dev server (?)

Did you also build the bundle? Your repro is missing a `yarn react-native bundle ...` step.

**Comment by alfonsocj** [comment]
- Is not really because detox requires it. More like we want to test in CI without having a dev server.

> Did you also build the bundle? Your repro is missing a yarn react-native bundle ... step.

🤔Doesn’t `gradlew assembleRelease` bundle automatically?

**Comment by tido64** [comment]
It doesn't in `react-native-test-app`. We separated that out as we don't want to take the hit on bundling when nothing has changed, or when you're using the dev server anyway, which is most of our usage scenarios.

**Comment by alfonsocj** [comment]
That makes sense! Thanks for the explanation

**Comment by tido64** [comment]
> That makes sense! Thanks for the explanation

No problem 😉
