### ISSUE TITLE
Add support for macOS Big Sur

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#129]
[macOS Big Sur](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/) was [announced](https://www.apple.com/newsroom/2020/06/apple-introduces-macos-big-sur-with-a-beautiful-new-design/) at WWDC 2020. We should make sure our macOS test app is compatible with it, and that we can compile Universal 2 binaries.

**Comment by Saadnajmi** [comment]
I believe @HeyImChris is working on this, just an FYI

**Comment by HeyImChris** [comment]
React-native-macOS builds for Xcode 12 Beta 4 right now. I'm working on integrating it to downstream Office clients, but the public repo should be all set. I'll keep watching it/updating it as new betas come out until we're on a stable version of Xcode 12. Going to close as RN runs on a Silicon machine in its current state.

**Comment by tido64** [comment]
@HeyImChris: That's awesome! Does that mean we need only use the latest version of `react-native-macos`? Did you get a chance to check whether `react-native-test-app` works as expected?

**Comment by Saadnajmi** [comment]
Just an FYI, I'll be looking at this as well soon for adding ARM64 support on macOS for FluentUI React Native. I may end up sending a PR to edit some xcconfigs on that end
