### ISSUE TITLE
Add ability to change app bundle ID

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#140]
The current app bundle ID is `com.react.testapp` for Android, and `com.microsoft.ReactTestApp` for iOS and macOS. This is an issue if users want to implement auth (see https://github.com/microsoft/react-native-test-app/pull/139#discussion_r448449855), or want to publish to the App Store. Users need a way to change the bundle ID.

**Comment by sweggersen** [comment]
Could we add an option to app.json? appBundleId/packageName

**Comment by tido64** [comment]
Yeah, I was thinking of adding `appBundleId` to the manifest as well. @acoates-ms, do you have any thoughts around this?

**Comment by tido64** [comment]
Alternatively, it could also go into the `build.gradle`/`Podfile`…
