### ISSUE TITLE
If complex `initialProperties` is set in `app.json` app fails to boot properly

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-test-app#144]
The `Manifest.swift` offers the ability to set an `initialProperties` in the `app.json` and the intention is that the dictionary is passed to the `initialProperties` argument of the `RCTRootView` or `RCTBridge`.   However, only `initialProperties` that contain simple String:String pairs work.   But if `initialProperties` contains sub objects it fails to boot.

Changing the Swift type from `[String: String]?` to `[AnyHashable: Any]?` would be ideal, but that makes the object fail to conform to `Codeable`.

**Comment by tido64** [comment]
@ArazAbishov: Does this bug also affect Android? Seems like we only support `Map<String, String?>` as well: https://github.com/microsoft/react-native-test-app/blob/fa50591dfcbf7d760db1b5ad37137f2321b4e9db/android/app/src/main/java/com/react/testapp/manifest/Manifest.kt#L16

**Comment by ArazAbishov** [comment]
@tido64 correct, it affects Android too. I can take a look at it.
