### ISSUE TITLE
Quick start wiki has incorrect command in Macos section

### ISSUE THREAD

**Issue by mandrade2** [microsoft/react-native-test-app#1697]
### What happened?

The command listed in the Quickstart for macos is `yarn build:ios` but it should be `yarn build:macos`. 

See https://github.com/microsoft/react-native-test-app/wiki/Quick-Start#macos

### Version

0.71

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
It's on the Github Wiki
```

### Steps to Reproduce

See docs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for letting us know! It should be fixed now.
