### ISSUE TITLE
Generate code from `app.json` and avoid parsing JSON at runtime

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#1722]
### Proposal

We currently parse `app.json` at runtime. However, **`app.json` does not change at runtime**, so it doesn't really make sense that we have to parse it at runtime either. Additionally:

- On some platforms, this requires additional dependencies ([Moshi + KSP](https://github.com/square/moshi) on Android, [JSON for Modern C++](https://github.com/nlohmann/json) on Windows) that we have to keep up to date.
- On Android, there is additional maintenance overhead because KSP is tied to specific versions of Kotlin. In order to allow users to specify their own Kotlin version, we need to keep a list of supported KSP versions.

If we can generate code from `app.json` that we can embed directly in the app, we can eliminate the need for a JSON parser altogether.

### Alternatives

n/a

### Implementation Details

- [x] Android: https://github.com/microsoft/react-native-test-app/pull/1979
- [x] iOS/macOS/visionOS: https://github.com/microsoft/react-native-test-app/pull/1985
- [x] Windows: https://github.com/microsoft/react-native-test-app/pull/1984

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by saram-aman** [comment]
Is it still open?

**Comment by tido64** [comment]
> Is it still open?

Yes

**Comment by tido64** [comment]
All shipped as of [3.5.15](https://github.com/microsoft/react-native-test-app/releases/tag/3.5.15)
