### ISSUE TITLE
Improve the docs: add npm examples

### ISSUE THREAD

**Issue by edodusi** [microsoft/react-native-test-app#1756]
### Proposal

In the wiki section, the documentation is clear and exhaustive, but all the examples are done with `yarn`.

It would be great to add examples using `npm` as well, and give the reader a way to switch between the two: for many snippets, simply replacing `yarn` with `npm` is not enough, as it's clear from the init command that using npm becomes `npm exec init-test-app`.

### Alternatives

I don't know all the possibilities offered by the GitHub wiki, but the ideal solution would be a snippet widget with tabs to switch between yarn and npm, like the react-native docs.

An alternative would be to just present the two snippets one after the other.

### Implementation Details

This requires a change to the wiki docs, unfortunately I cannot do a PR 🥲. 

### Additional Context

![example 1](https://github.com/microsoft/react-native-test-app/assets/2177962/f1b3ae7b-09ed-421c-a925-c09a40d62fb7)

![example 2](https://github.com/microsoft/react-native-test-app/assets/2177962/43461030-4e25-4b08-8572-1ce5d94593f2)

(PS: it would also be great to have an additional template for GH issues for the docs or general feedback!)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelset** [comment]
Thanks for the feedback Edo! We'll look into it :)

**Comment by tido64** [comment]
I had a look around and it doesn't look like GitHub supports tabs today. It has been requested though (see [[1](https://github.com/github/markup/issues/1552)][[2](https://github.com/orgs/community/discussions/17381)]). For now, I've added npm instructions right after [the Yarn ones](https://github.com/microsoft/react-native-test-app/wiki/Quick-Start).

Really appreciate that you took the time to file this. Let us know if you find other issues. :heart:

**Comment by edodusi** [comment]
Thanks @tido64!
