### ISSUE TITLE
iOS / Android Assets

### ISSUE THREAD

**Issue by rthic23** [microsoft/react-native-test-app#1813]
### Proposal

I would like to add assets to native iOS and Android in test app like fonts, mp3 files etc. 

### Alternatives

https://github.com/unimonkiez/react-native-asset

### Implementation Details

I'm using https://github.com/unimonkiez/react-native-asset to inject and link the assets in iOS and Android. But I want to use this library inside your test app. Can you provide an alternate to this on how to inject fonts and link it on both iOS and Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelset** [comment]
can you provide a sample repro of a RNTA example up + this lib + some asset to inject so that we can have a look?

it'd also be useful to understand better your use case.

**Comment by tido64** [comment]
+1

It would be great to know what your use cases are so we can prioritize appropriately. Certain types should already be supported, but there are types that must be handled differently. An example of this is embedding custom fonts: https://github.com/microsoft/react-native-test-app/issues/1185

I've collected some thoughts here: https://github.com/microsoft/react-native-test-app/wiki/Assets

**Comment by rthic23** [comment]
> can you provide a sample repro of a RNTA example up + this lib + some asset to inject so that we can have a look?
> 
> it'd also be useful to understand better your use case.

Thanks for quick response!.
**Purpose for using RNTA:**
 I'm currently not using RNTA. Im using regular RN template app(no EXPO) with [react-native-asset](https://github.com/unimonkiez/react-native-asset) lib to inject fonts (npx react-native-asset -  runs script in Native folders to transfer the fonts) in Native iOS and Android. Disadvantage of this repo is for every RN major upgrade I had to manually update the folders for android and iOS. So I want to transition to RNTA where the RN upgrades is seamless.

**Problem** 
My use case is adding .otf fonts or .mp3. Right now im using [asset library ](https://github.com/unimonkiez/react-native-asset?tab=readme-ov-file#usage)to link the assets in regular RN template app.

**Solution I need**
But i want to use RNTA. But RNTA doesnt include android or iOS folders. react-native-asset library doesnt work here without the platform folders to link the assets. so i was asking for a way to add fonts similar to that library. 

Seeing the below link I did see its an ongoing effort(Thank you!). Is there any timeline or particular release I should expect?
https://github.com/microsoft/react-native-test-app/wiki/Assets

**Comment by tido64** [comment]
> Is there any timeline or particular release I should expect?

I wish we could give you a date, but between internal priorities and other things that come up during the weekdays, it's hard to say exactly when we will have time to work on this. If you're able to contribute, that's easily the fastest way right now. I can provide pointers as needed. The alternative is to use [config plugins](https://docs.expo.dev/guides/config-plugins/) as I'd suggested in https://github.com/microsoft/react-native-test-app/issues/1185 to unblock yourself in the meantime.

**Comment by tido64** [comment]
@Karthiccc23 Would you mind testing #1828 and see if your fonts and audio load?

**Comment by rthic23** [comment]
> @Karthiccc23 Would you mind testing #1828 and see if your fonts and audio load?

awesome!! Sorry for the late response had some work to catchup. I will definitely test this feature by this week and let you know the results. Thanks again!! 👍

**Comment by rthic23** [comment]
> @Karthiccc23 Would you mind testing #1828 and see if your fonts and audio load?

Tested fonts. Thank you!
