### ISSUE TITLE
Adding Cocoapods minimum version requirement when setting up a project

### ISSUE THREAD

**Issue by floydkim** [microsoft/react-native-test-app#1817]
### Proposal

Hello. Thanks for your great contribution to the RN community.
I'm trying RNTA for the first time today.

I ran the `npx --package react-native-test-app@latest init` command and followed the prompts.
(checked all of supported platforms)
After the project was created, I ran `npm install` and tried to build iOS and macOS targets.

I have encountered several errors similar to the one below when running `pod install` from the `/ios` and `/macos` directories.
`undefined method 'visionos'`
```
[!] Failed to load 'React-RCTFabric' podspec: 
[!] Invalid `React-RCTFabric.podspec` file: undefined method `visionos' for #<Pod::Specification name="React-RCTFabric">.
```

After spending some time with it, I realized that these errors were due to the version of Cocoapods.
(I'm using version 1.12.1)
After using Cocoapods 1.13.0, the dependency installation completed without any issues.

There was a change regarding visionOS support in each package, and I noticed that it is supported starting with Cocoapods 1.13.0.

### Alternatives

Is it possible to help developers by ensuring that projects created with `npx react-native-test-app` use the recommended cocoapods version, for example by using a Gemfile?

### Implementation Details

(1) Add Gemfile to `/ios` `/macos`

kind of..
```ruby
source 'https://rubygems.org'

gem 'cocoapods', '>= 1.13', '< 1.15'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'

```

(2) Add a `bundle install` step to the instruction

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saadnajmi** [comment]
Good catch! I guess by adding visionOS Support, we have also raised the cocoapods minimum to 1.13. It might be sufficient to start with just adding a note to docs, before adding a gemfile since people have many different ways to install cocoapods

**Comment by tido64** [comment]
Can we conditionally add visionOS in the `.podspec`? Something like `s.visionos.framework = ... unless s.visionos.nil?`

**Comment by Saadnajmi** [comment]
> Can we conditionally add visionOS in the `.podspec`? Something like `s.visionos.framework = ... unless s.visionos.nil?`

Most of the React Native macOS pod specs use a helper function "min_supported_versions" that just lists iOS, macOS, and visionOS. There might be a condition we can check and override that method.

**Comment by tido64** [comment]
@floydkim Thanks for reporting this. I've added a check that tells the user to upgrade on `pod install`. Seems to be the most universal since not all users use `Gemfile` to manage CocoaPods. This fix should be out soon.

**Comment by floydkim** [comment]
@tido64 Wow, that's a quick fix, thank you so much.
