### ISSUE TITLE
Fresh install fails on Windows (Latest version as of this issue)

### ISSUE THREAD

**Issue by karimb11** [microsoft/react-native-test-app#1849]
### What happened?

When you run `npx --package react-native-test-app@latest init` On Windows, it produces the following error:

```
√ What is the name of your app? ... TestApp
√ Where should we create the new project? ... TestApp
No version was specified; fetching available versions...
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at spawnSync (node:child_process:876:24)
    at npm (XXX\AppData\Local\npm-cache\_npx\c889b7c64cc944be\node_modules\react-native-test-app\scripts\init.js:29:37)
    at XXX\AppData\Local\npm-cache\_npx\c889b7c64cc944be\node_modules\react-native-test-app\scripts\init.js:138:28
```

I had to edit the line at `scripts\init.js:29:3` and do `spawnSync("npm.cmd"...` instead of `spawnSync("npm"...` to get it to work.

### Version

3.2.5

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
`npx react-native info` no longer works as of version `0.73.4`
```

### Steps to Reproduce

Check issue message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for reporting this! This is a gap in our testing that we had missed.
