### ISSUE TITLE
Is react-native-test-app's only use case: library testing or can it be used for production apps as well

### ISSUE THREAD

**Issue by karimb11** [microsoft/react-native-test-app#1853]
### Proposal

If the latter is true, I think a different name would have been more impactful for discoverability.

### Alternatives

.

### Implementation Details

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
It certainly started out that way but has evolved over the years. In recent versions, you can enable "single-app mode" to put RNTA in "production" mode. See the wiki entry for more details: [Single-app Mode](https://github.com/microsoft/react-native-test-app/wiki/Single-app-Mode)

**Comment by kelset** [comment]
thanks for asking @karimb11! We are aware of the naming/discoverability angle but for now the primary use case is still very much to create a stable sandbox environment for developers working on libraries and similar use cases. As Tommy mentioned, we do have this "production mode" feature and if you want to give it a go, please let us know how that goes!

We might actually go down this "production" route further down in the future, so keep your eyes open for that ;)
