### ISSUE TITLE
React Native 0.74.1 and new architecture + bridgeless results in a soft crash `SurfaceRegistryBinding::startSurface failed. Global was not installed.`

### ISSUE THREAD

**Issue by kraenhansen** [microsoft/react-native-test-app#2015]
### What happened?

![Simulator Screenshot](https://github.com/microsoft/react-native-test-app/assets/1243959/1bf373e2-921e-4224-8791-96b3a8f52442)

### Version

3.7.0

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] visionOS
- [ ] Windows

### System Information

```true
System:
  OS: macOS 14.4.1
  CPU: (14) arm64 Apple M3 Max
  Memory: 147.72 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.0
    path: ~/Library/Caches/fnm_multishells/75556_1714746688416/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/Library/Caches/fnm_multishells/75556_1714746688416/bin/npm
  Watchman:
    version: 2024.04.29.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Steps to Reproduce

1. `npx --package react-native-test-app@latest init --platform ios --platform android --name Sanity --destination sanity`
2. `cd sanity`
3. `npm install`
4. `cd ios && RCT_NEW_ARCH_ENABLED=1 pod install && cd -`
5. In one terminal, start the dev server (`npm start` in `sanity`)
6. `npm run ios` to build and start the app
7. Observe "(NOBRIDGE) LOG  Bridgeless mode is enabled" in the log of the Metro bundler and see soft crash (attached as screenshot).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @kraenhansen, I was not able to reproduce this:

![image](https://github.com/microsoft/react-native-test-app/assets/4123478/1600e53c-89e5-4f7e-a102-ec68b037b99d)

I also stepped through the code and it looks like this is something that would happen if bundling failed:

![image](https://github.com/microsoft/react-native-test-app/assets/4123478/d5c27f8c-70fb-4e5b-a2f6-d9bcf173f381)

On line 47, if `RN$AppRegistry` is not an object, it would to into the else block on line 56 and throw the exception you see there.

Did you create a bundle or start a dev server? I don't see it in your repro steps.

**Comment by kraenhansen** [comment]
I start a dev server, will update the steps and run though them once again on Monday 👍

**Comment by kraenhansen** [comment]
I just re-ran the steps from the top with a different app name and directory to prune any implicit build caches, but I'm still reproducing it. I see your screenshot is running Metro 0.80.4, mine is 0.80.9, what does your `npm ls` yield?

```bash
❯ npm ls
Sanity2@0.0.1 /Users/kraen.hansen/Repositories/sanity2
├── @babel/core@7.24.5
├── @babel/preset-env@7.24.5
├── @babel/runtime@7.24.5
├── @react-native/babel-preset@0.74.83
├── @react-native/eslint-config@0.74.83
├── @react-native/metro-config@0.74.83
├── @react-native/typescript-config@0.74.83
├── @rnx-kit/metro-config@1.3.15
├── @types/react-test-renderer@18.3.0
├── @types/react@18.3.1
├── babel-jest@29.7.0
├── eslint@8.57.0
├── jest@29.7.0
├── prettier@2.8.8
├── react-native-test-app@3.7.0
├── react-native@0.74.1
├── react-test-renderer@18.2.0
├── react@18.2.0
└── typescript@5.0.4
```

Also, what's your `Xcode` version? (I have no clue if that could influence this - but I'm on `15.3`).

From your screenshot, it looks like you're testing with [the `example` app](https://github.com/microsoft/react-native-test-app/blob/trunk/example/package.json) of your repository instead of generating a new app via the steps I provided.

**Comment by kraenhansen** [comment]
For reference, I tried but failed to reproduce it with [the example app](https://github.com/microsoft/react-native-test-app/blob/trunk/example/package.json).

**Comment by tido64** [comment]
You're right. It looks like there's a race condition. If you dismiss the red box, navigate back, then reopen the view, it will render just fine. It looks like a core bug to me, but I can take a closer look later. Maybe @cipolleschi has more ideas?

**Comment by tido64** [comment]
Confirmed to be a bug in `@rnx-kit/react-native-host`. We will hopefully get this addressed within the day or so.

**Comment by kelset** [comment]
Hey Kraen sorry for the delay, had a bunch of issues with my local Xcode / Simulator setup and yesterday was bank holiday here in UK - I was able to repro thanks to your detailed steps:

<img src="https://github.com/microsoft/react-native-test-app/assets/16104054/6acfd7fb-d432-45b0-8ca5-2703c7938766" alt="broken" width="200"/>

And also able to verify that the fix Tommy made in the PR https://github.com/microsoft/rnx-kit/pull/3130 addresses this:

<img src="https://github.com/microsoft/react-native-test-app/assets/16104054/01ca1cff-f759-4f62-8350-7b4d58967bc5" alt="fixed" width="200"/>

**Comment by tido64** [comment]
This fix is now published. You can either manually bump `@rnx-kit/react-native-host` to 0.4.9, or wait for 3.7.2. It should be out within the hour.

**Comment by kraenhansen** [comment]
Awesome! Thanks for the quick turnaround (again) 🙂

**Comment by RichardLindhout** [comment]
I had this crash en it was fixed after installing expo-dev-client somehow...

**Comment by Grohden** [comment]
Having this one with expo dev client, nothing related to this package tho

**Comment by RohovDmytro** [comment]
> Having this one with expo dev client, nothing related to this package tho

+1.

React Native 0.77.0 + expo-dev-client

**Comment by TasseDeCafe** [comment]
Most likely unrelated to the original bug mentioned by OP, but since it's the only place online that mentions this specific bug, I would love to have any sort of clue about how I could debug this. In my case, it happens after I update some packages, but it's unclear which ones exactly. Installing them one by one produces confusing results.

**Comment by Grohden** [comment]
@TasseDeCafe I managed to solve, unfortunately I have no clue when or how since I got so many issues adopting expo stuff

However, a friend of mine is now doing the same work I did in the past and he managed to isolate this to him adding the expo-dev-client package which Ive already mentioned)

If I had to guess I probably forgot to add the top level import of the package... or I did a really good cleanup of caches and such and it vanished

**Comment by Grohden** [comment]
My colleague was just able to make it work, it seems that when we added expo dev client we also need to add expo constants (or expo assets), thats our best guess 🤷

**Comment by TasseDeCafe** [comment]
@Grohden thanks for the reply. I actually found the origin of the problem for me yesterday. The issue was that my Metro config was incorrect in the context of my Turborepo monorepo.

I fixed this by following the template of Turborepo for react native.

The fix was simple but the error was so cryptic that I spent almost 3 days on it...

**Comment by RohovDmytro** [comment]
> [@Grohden](https://github.com/Grohden) thanks for the reply. I actually found the origin of the problem for me yesterday. The issue was that my Metro config was incorrect in the context of my Turborepo monorepo.
> 
> I fixed this by following the template of Turborepo for react native.
> 
> The fix was simple but the error was so cryptic that I spent almost 3 days on it...

What was wrong with the config?..

**Comment by TasseDeCafe** [comment]
Here is what Turborepo does in their default template:

```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const path = require("path");

// Find the workspace root, this can be replaced with `find-yarn-workspace-root`
const workspaceRoot = path.resolve(__dirname, "../..");
const projectRoot = __dirname;

const config = getDefaultConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot];
// 2. Let Metro know where to resolve packages, and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;

module.exports = config;
```

**Comment by James-Prescott** [comment]
Derived from @TasseDeCafe's comment (thanks!), I only had to add `disableHierarchicalLookup: true` to my metro config to solve this issue for me.

**Comment by Sechorda** [comment]
> Most likely unrelated to the original bug mentioned by OP, but since it's the only place online that mentions this specific bug, I would love to have any sort of clue about how I could debug this. In my case, it happens after I update some packages, but it's unclear which ones exactly. Installing them one by one produces confusing results.

This is my case as well, getting it on 0.79.5
