### ISSUE TITLE
Allow targeting any number of supported platforms

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#233]
The Plop template only allows one to choose all or one platform:

```
% yarn plop --dest example
? What is the name of your test app? Example
? Which platforms do you need test apps for? (Use arrow keys)
❯ all
  android
  ios
  macos
  windows
```

We should allow users to pick any platform they want, e.g.:

```
% yarn plop --dest template-example
? What is the name of your test app? Example
? Which platforms do you need test apps for? (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◉ android
 ◉ ios
 ◉ macos
 ◉ windows
```

- [ ] It would be really nice if we could pre-select the supported platforms. Maybe `react-native config` can help us find out?
- [ ] If we can detect supported platforms, we should also update the React Native CLI command (see https://github.com/microsoft/react-native-test-app/pull/232#discussion_r499751609) to provide a better default.

**Comment by thriftykapila** [comment]
I am interested to this task, I am React Js developer and I have worked with React Native earlier as well. Please assign me this issue.

**Comment by tido64** [comment]
@thriftykapila It's all yours. Thanks!
