### ISSUE TITLE
iOS: Background view is always white, doesn't respect dark mode

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-test-app#285]
### Description

When you launch a component, the background of the component view is white. This is usually obscured by the react native view rendered on top of it, but it bleeds through into the Header, which is noticecably lighter.

https://user-images.githubusercontent.com/6722175/109762381-1914f400-7bb6-11eb-936c-d7ad13f5f55f.mov

### Your environment

* `react-native-test-app` version: 0.3.2
* Tested platforms:
  * [ ] Android
  * [x] iOS
  * [ ] macOS
  * [ ] Windows
* System information:
  
  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 185.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1.1 4.1.1
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Saadnajmi** [comment]
Note: Even if I set my React-Native View to have a black background, there is still a white RCTRootView behind it, as seen in this screenshot. Worth noting that in this case my React-Native View is just that tiny black view a little bigger than the header (because all it has is "Hello World")

![Screen Shot 2021-03-03 at 12 20 33 AM](https://user-images.githubusercontent.com/6722175/109762738-b708be80-7bb6-11eb-94fc-65d98b102f7b.png)

**Comment by tido64** [comment]
It looks like `RCTRootView` always [sets white background color](https://github.com/facebook/react-native/blob/master/React/Base/RCTRootView.m#L61). Can you see if this helps?

```diff
diff --git a/ios/ReactTestApp/ContentView.swift b/ios/ReactTestApp/ContentView.swift
index 3cf3e2e..32c7761 100644
--- a/ios/ReactTestApp/ContentView.swift
+++ b/ios/ReactTestApp/ContentView.swift
@@ -186,6 +186,7 @@ final class ContentViewController: UITableViewController {
                 moduleName: component.appKey,
                 initialProperties: component.initialProperties
             )
+            viewController.view.backgroundColor = UIColor.systemBackground
             return viewController
         }()
 
```

**Comment by Saadnajmi** [comment]
@tido64 That worked! Thank you =) 
As a workaround, I'll just set the background of my app to fill space and be white/black in React Native.
