### ISSUE TITLE
Issue while creating a project [Expecting 'ID', got 'INVALID']

### ISSUE THREAD

**Issue by pruthvip** [microsoft/react-native-test-app#290]
### Description
I followed the steps given in the readme.
While running the following command, i am getting this error.

$ /Users/pruthvip/code/test-ms-rnta/node_modules/.bin/plop --plopfile node_modules/react-native-test-app/plopfile.js --dest sample
? What is the name of your test app? lpptestapp
? Which platforms do you need test apps for? all
⠋ [WARN] Cannot find module 'react-native-macos'; skipping macOS target
[WARN] Cannot find module 'react-native-windows'; skipping Windows target
✔  ++ /.watchmanconfig
✖  ++ Parse error on line 71:
...lors.black : Colors.white,          }}>
-----------------------^
Expecting 'ID', got 'INVALID'
✖  ++ app.json Aborted due to previous action failure
✖  ++ babel.config.js Aborted due to previous action failure
✖  ++ index.js Aborted due to previous action failure
✖  ++ metro.config.js Aborted due to previous action failure
✖  ++ package.json Aborted due to previous action failure
✖  ++ react-native.config.js Aborted due to previous action failure
✖  ++ android/gradle/wrapper/gradle-wrapper.jar Aborted due to previous action failure
✖  ++ android/gradle/wrapper/gradle-wrapper.properties Aborted due to previous action failure
✖  ++ android/gradle.properties Aborted due to previous action failure
✖  ++ android/gradlew Aborted due to previous action failure

### Your environment

* `react-native-test-app` version:
* Tested platforms:
  * [*] Android
  * [*] iOS
  * [*] macOS
  * [ ] Windows
* System information:
  
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 129.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1-alpha.2 => 5.0.1-alpha.2 
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: ^0.63.23 => 0.63.23 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tido64** [comment]
Thanks for reporting this issue ❤️ 

It looks like Plop is mistaking some tokens in the new `App.js` for variables it should replace. I will try to find a fix. In the meantime, you can work around this issue by making the following changes:

```diff
diff --git a/node_modules/react-native/template/App.js b/node_modules/react-native/template/App.js
index f85f38d87ad..5a217123897 100644
--- a/node_modules/react-native/template/App.js
+++ b/node_modules/react-native/template/App.js
@@ -59,6 +59,10 @@ const App: () => Node = () => {
     backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
   };
 
+  const innerBackgroundStyle = {
+    backgroundColor: isDarkMode ? Colors.black : Colors.white,
+  };
+
   return (
     <SafeAreaView style={backgroundStyle}>
       <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
@@ -67,9 +71,7 @@ const App: () => Node = () => {
         style={backgroundStyle}>
         <Header />
         <View
-          style={{
-            backgroundColor: isDarkMode ? Colors.black : Colors.white,
-          }}>
+          style={innerBackgroundStyle}>
           <Section title="Step One">
             Edit <Text style={styles.highlight}>App.js</Text> to change this
             screen and then come back to see your edits.
```
