### ISSUE TITLE
Android: Remove the remaining JCenter dependencies

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#305]
As a follow-up to [#278](https://github.com/microsoft/react-native-test-app/pull/278/files#r606641816), we need to remove the remaining `react-native` dependencies when they've been published to Maven Central.

**Comment by sweggersen** [comment]
@tido64 , do you know if the dependencies have been published to Maven Central? 

            includeGroup("com.facebook.fbjni")
            includeGroup("com.facebook.flipper")
            includeGroup("com.facebook.fresco")
            includeGroup("com.facebook.yoga")

**Comment by tido64** [comment]
> @tido64 , do you know if the dependencies have been published to Maven Central?

As far as I know, only the versions that 0.65+ depends on are uploaded. If we're targeting older versions, we still need to use JCenter.

**Comment by sweggersen** [comment]
Ok, thanks. Another reason to move to 0.65+.
