### ISSUE TITLE
Ensure compat of `test-app.gradle` with windows

### ISSUE THREAD

**Issue by ArazAbishov** [microsoft/react-native-test-app#32]
Check whether hardcoded path delimiters in gradle scripts are compatible with windows. Otherwise use File.separator.

**Comment by tido64** [comment]
Can we verify by setting up a pipeline that runs on Windows?

**Comment by ArazAbishov** [comment]
Yes, that's a good idea.

**Comment by ArazAbishov** [comment]
Done. Defined a pipeline for Windows and it seems to be building fine.
