### ISSUE TITLE
Error Running iOS test app: index.js is not a transformer

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-test-app#372]
### Description

I tried using `yarn init-test-app` to make a new RNTA-based test app for the community module react-native-menu. The test app builds and runs, but I get an error loading the bundle.

<img width="561" alt="Screen Shot 2021-06-25 at 5 02 58 PM" src="https://user-images.githubusercontent.com/6722175/123489534-d13c3180-d5d7-11eb-8830-b530b444b268.png">

### Your environment

* `react-native-test-app` version: 0.6.3
* Tested platforms:
  * [ ] Android
  * [x] iOS
  * [ ] macOS
  * [ ] Windows
* System information:
  
  ```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 921.95 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1.2 4.1.2
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: ^0.63.0 => 0.63.36 
  npmGlobalPackages:
    *react-native*: Not Found
  ```

### Steps to reproduce

```
git clone git@github.com:react-native-menu/menu.git
cd menu
mv example/ example2/ # This is to just move the existing test app out of the way temporarily
yarn add react-native-test-app --dev
yarn init-test-app
# The options I chose
# ✔ What is the name of your test app? … MenuExample
# ✔ Which platforms do you need test apps for? › Android, iOS, macOS
# ✔ Where should we create the new project? … example
yarn
cd ios
pod install
# open MenuExample.xcworkspace and build in xcode
yarn start
```

**Comment by tido64** [comment]
It looks like this could happen if you're using `metro` 0.59 for `react-native` 0.64 instead of `metro` 0.64. `react-native-macos` is still in 0.63, so it would pull in the older `metro` version. Even if you force Yarn to resolve to `metro` 0.64, `react-native-macos` won't work because the API has changed. You have to either downgrade `react-native` to 0.63, or remove `react-native-macos`.

**Comment by Saadnajmi** [comment]
Ah, good to know, thank you.  Thank you for doing that investigation. I'll probably wait till `react-native-macos` is on 0.64 then

**Comment by tido64** [comment]
> Ah, good to know, thank you. Thank you for doing that investigation. I'll probably wait till `react-native-macos` is on 0.64 then

You can still add it now with only Android and iOS support. Then add support for `react-native-macos` later with `yarn configure-test-app --platforms macos`.

**Comment by Saadnajmi** [comment]
Yep, that was my fallback plan! Still a worthy addition =)

**Comment by tido64** [comment]
Cool! Let me know if you need any help. In the meantime, I'll see if I can add some warnings for when there's a version mismatch.
