### ISSUE TITLE
Add .gitignore with `init-test-app`

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-test-app#374]
### Proposal

Running `yarn init-test-app` didn't copy a .gitignore for me when I ran it. This meant that things like `dist/` and `example.xcworkspace` were showing up as available to be added to git. 

I ended up copying the one from this repo's example app for my local project. It would be nice if that's copied over.

### Additional context

Found while trying to move this module to RNTA: https://github.com/react-native-menu/menu

**Comment by Shivakumar-SG** [comment]
Hey, @Saadnajmi 
I would like to take up this issue as my first contribution to OSS! Would you please guide me through it?

**Comment by Saadnajmi** [comment]
Hello @Shivakumar-SG , I'm not an owner of this repo, so I haven't actually made a lot of changes here / know it's structure well. Someone else like @tido64 or @arazabishov might be better! However, I imagine you would probably want to start here https://github.com/microsoft/react-native-test-app/blob/trunk/scripts/configure.js
Probably add it to the common configuration? https://github.com/microsoft/react-native-test-app/blob/f87322599c8c0d4b0a510616ae1caf5b5f4978c4/scripts/configure.js#L287

**Comment by tido64** [comment]
@Shivakumar-SG: Feel free to submit a PR 👍 

We probably want to copy both `/example/.gitignore` and `/example/windows/.gitignore`. The latter contains ignore rules for Visual Studio outputs. Once you've added them to the configure script, you'll also need to add them to `/.npmignore` to make sure they are included in the published packages.

**Comment by Shivakumar-SG** [comment]
I thought of figuring out how the rest of the files were getting copied to the test app so that I can do the same for the mentioned .gitignore files but I could not able to trace them back. And if I try to remove one of the files getting copied by commenting it out or by removing, it still gets created in common files. Would you mind helping me with how these `babel.config.js`, `metro.config.js`, etc. are copied?

**Comment by tido64** [comment]
@Shivakumar-SG: Can you please take a look at this PR and let me know if it has enough information for you: https://github.com/microsoft/react-native-test-app/pull/388

It is important for us that we have sufficient documentation in place so people can get up and running fast 😄

**Comment by tido64** [comment]
Addressed by #389
