### ISSUE TITLE
No auth redirect for Android APKs built on Windows

### ISSUE THREAD

**Issue by sveinar** [microsoft/react-native-test-app#409]
The onActivityResult is missing in the ComponentActivity.java. It was removed in 0.6.3 and now we are not seeing the redirectUrl working on Windows. It does work fine for me on MacOS, but for Windows - there is no redirection happening.

The root cause appears to be the lack of the `onActivityResult` method that existed in earlier versions like this:

```
   override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        supportFragmentManager.fragments.forEach {
            it.onActivityResult(requestCode, resultCode, data)
        }
    }
```

@arazabishov , do you know the rationale behind this removal? Maybe we need to introduce another step in any support libraries for handling the auth code forwarding to the fragments down the chain?

**Comment by arazabishov** [comment]
Hey @sveinar! Sorry to hear that. Could you please provide a little bit more context? I do not understand how macOS/Windows can affect behaviour from within the Android environment?

**Comment by sveinar** [comment]
Same here, super-funky that there is a difference between MacOS and Windows. And I believe the reason for it has nothing to do with the platform per se. On Windows, my device is very thorough and slow, so there is no React context yet. As such, with no react context, there is no forwarding of auth as there are no listeners...resulting in no auth redirects happening as getCurrentReactContext returns null in this case.

An interesting error condition for slow devices on init?
It appears to be working in 0.5.7 though.
