### ISSUE TITLE
Android: options to load the bundle either from the dev server or assets

### ISSUE THREAD

**Issue by ArazAbishov** [microsoft/react-native-test-app#53]
The iOS test-app has two UI options to choose the bundle source. Android should have support for the same feature. 

![image](https://user-images.githubusercontent.com/4133693/78452257-97a5a080-768a-11ea-87ab-cc4ca9d35ee8.png)

**Comment by tido64** [comment]
Note that "Load From Dev Server" becomes "Scan QR Code" when run on device.
