### ISSUE TITLE
MacOs build Failed

### ISSUE THREAD

**Issue by shubhamcloud9** [microsoft/react-native-test-app#542]
### What happened?

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

/bin/bash: line 7: 
: command not found
Error: Process completed with exit code 1.

### Version

0.9.0

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

/bin/bash: line 7: 
: command not found
Error: Process completed with exit code 1.
```

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/89636139/136740324-fd1ce81e-8453-4a0a-b515-0e141787e501.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi, are you using canary builds of `react-native-macos`? I don't see how the screenshot under "Steps to Reproduce" is relevant to this issue as it shows Yarn having network trouble.

**Comment by tido64** [comment]
If you're using `react-native-macos` canaries: https://github.com/microsoft/react-native-macos/issues/850

**Comment by shubhamcloud9** [comment]
Fixed
https://github.com/microsoft/react-native-test-app/runs/3881674349?check_suite_focus=true
