### ISSUE TITLE
Could not create project for macos or windows 

### ISSUE THREAD

**Issue by edfungus** [microsoft/react-native-test-app#573]
### What happened?

Installing this for the first time with all platforms selected and can't seem to create for macos and windows. I get the following logs:

```
√ What is the name of your test app? ... test
√ Which platforms do you need test apps for? » Android, iOS, macOS, Windows
√ Where should we create the new project? ... test
[!] react-native-macos@0.66 cannot be added because it does not exist or is unsupported
[!] react-native-windows@0.66 cannot be added because it does not exist or is unsupported
Done in 12.72s.
```

OS: Windows 11

### Version

0.9.10

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [X] Windows

### System Information

```true
`wmic` is deprecated from Windows 11 for `npx react-native info` doesn't work. Let me know if there is something else I can run
```

### Steps to Reproduce

```
yarn add react-native
yarn add react-native-test-app --dev
yarn init-test-app
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for reporting this! You shouldn't have gotten the complaint for `react-native-windows`. I've just submitted a fix for it. As for `react-native-macos`, unfortunately, the [latest version is 0.63](https://www.npmjs.com/package/react-native-macos). The app initializer requires all platforms to be aligned. We've seen too many issues with `react-native` versions being unaligned in the past, so we just don't support that scenario. You should be able to create an app without `react-native-macos` though (after the PR merges).
