### ISSUE TITLE
Support libraries based on JSI modules (Android)

### ISSUE THREAD

**Issue by jsamr** [microsoft/react-native-test-app#581]
### Proposal

First of all, thanks to all the contributors for this great tool! As far as I understand it, it doesn't support libraries such as `react-native-reanimated` on Android because they require special setup, such as tampering with `MainApplication.java`.  

### Alternatives

A bare React Native project.

### Implementation Details

The tool could check for entries in `rnx-kit` (package.json) such as `animation` and provide the setup files matching the current `react-native` version. Some additional setup might be required by hand; for example adding a babel plugin in `babel.config.js`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for the suggestion, @jsamr. I think this is a really good idea. I'm following up with some folks to make sure the JSI stuff is stable enough before we implement this. I also think that this is something that we should get into `@react-native-community/cli` as part of auto-linking. That way we don't lock the feature to this tool. I will keep you posted.

**Comment by tido64** [comment]
Closing this in favour of https://github.com/react-native-community/cli/issues/1527 and https://github.com/reactwg/react-native-new-architecture/discussions/2#discussioncomment-2388444. Please voice your concerns/questions/suggestions there.
