### ISSUE TITLE
mechanism to set app icon, app version

### ISSUE THREAD

**Issue by TomSwift** [microsoft/react-native-test-app#990]
### Proposal

As far as I can tell, there isn't an existing way to specify/provide an app icon.   On iOS (my primary target) the installed app uses the default icon provided by XCode.

It would be nice to be able to specify the path to an icon in the app.json manifest, and have that be used.

Similarly I don't see a way to specify the app version.   On iOS this is stored in the info.plist file, which is part of the react-native-test-app dependency.   Not being able to change the version number makes it difficult to make builds that can be uploaded to TestFlight for distribution.

It would be nice to be able to specify the app version in the app.json manifest.

### Alternatives

n/a

### Implementation Details

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Reopening for app icon support
